### ISSUE TITLE
右键菜单排序的问题

### ISSUE THREAD

**Issue by flybirdxx** [yolain/ComfyUI-Easy-Use-Frontend#3]
这个右键菜单我是真的喜欢,就是有个建议,乱神能不能把自动排序加个开关,以前的乱序看习惯了,插件装多了,现在要找插件有点费劲,
![image](https://github.com/user-attachments/assets/5696d3bb-4c1b-4137-af24-0e0a06e657b2)
希望能采纳哈,没有也没关系ovo

**Comment by yolain** [comment]
有开关。在设置中Easyuse 第一个
